name: Build cadvisor

on:
  push:
    branches:
      - master

jobs:
  build-arm64-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ARM64 Version
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cadvisor-arm64:latest

  build-amd64-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push AMD64 Version
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cadvisor-amd64:latest
  
  combine-two-images:
    runs-on: ubuntu-latest
    needs:
      - build-arm64-version
      - build-amd64-version
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Combine two images
        run: |
          docker manifest create ${{ secrets.DOCKERHUB_USERNAME }}/cadvisor:latest --amend ${{ secrets.DOCKERHUB_USERNAME }}/cadvisor-amd64:latest --amend ${{ secrets.DOCKERHUB_USERNAME }}/cadvisor-arm64:latest
          docker manifest push ${{ secrets.DOCKERHUB_USERNAME }}/cadvisor:latest